### ISSUE TITLE
Support of Chinese variable name?

### ISSUE THREAD

**Issue by cyfex** [java-decompiler/jd-gui#254]
Hi there, first of all, it's a great tool and thank you for the effort. However, I find something quite annoyed: when I try to decompile some Chinese java apps, as they contain Chinese class/method name, the decompiled code has something like 

/* renamed from: 保存列表 reason: contains not printable characters */
    public C0036 f84;

 everywhere, resulting in the obfuscated class name C0036 and variable name f84 across the code. Does jd-gui supports other character encoding? If not, why not? Is there any solution at hand to help me deobfuscate and restore those Chinese variable names?

**Comment by emmanue1** [comment]
Hi. Thank you for your message. You are not the first to that. Could you share a CLASS file so that I investigate?

**Comment by Yun-Shan** [comment]
### Non-English variable name
I just test Chinese and Russian variable name, compile with command `javac -encoding UTF-8 Test.java` and decompile with jd-gui-1.6.2, and it works fine!
here's my test code
```java
public class Test {
    public static final String 测试 = "test: Chinese variable name";
    public static final String 保存列表 = "test: Chinese variable name";
    public static final String Prøve = "test: Danish variable name";
    public static final String тест = "test: Russian variable name";
}
```
and here's the jd-gui decompiled result
![non-english result](https://i.loli.net/2019/07/08/5d224b674b63b43564.png)

### Unprintable characters
some obfuscators will use illegal characters(illegal for java but not for jvm) to rename variable, so that's a test.
I use ASM-7.0 to create a class which has illegal variable name
```java
        ClassWriter cw = new ClassWriter(Opcodes.ASM7);
        cw.visit(Opcodes.V1_8, Opcodes.ACC_PUBLIC, "Test", null, null, null);
        cw.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC | Opcodes.ACC_FINAL, "\u0001\u0002\u0003", "Ljava/lang/String;", null, "test: Unicode Control Characters variable name");
        cw.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC | Opcodes.ACC_FINAL, "\u200b", "Ljava/lang/String;", null, "test: Not Zero-Width Space variable name");
        cw.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC | Opcodes.ACC_FINAL, "\ufeff", "Ljava/lang/String;", null, "test: Not Zero-Width No-Break Space variable name");
        Files.write(Paths.get("Test.class"), cw.toByteArray());
```
and here's the decompiled result with  jd-gui-1.6.2
**Uncheck `Escape unicode characters`:**
![illegal characters result(check Escape unicode characters)](https://i.loli.net/2019/07/08/5d2259175869b79472.png)
**Check `Escape unicode characters`:**
![illegal characters result(uncheck Escape unicode characters)](https://i.loli.net/2019/07/08/5d2259177344375417.png)

**I think jd-gui has already do what it should do.**

### Conclusion
If you are troubled by non-English characters, Maybe update your jd-gui to version 1.6.2 will solve your problem.
If you are troubled by Illegal characters, you can use ProGuard to obfuscate the jar file again, only use the rename function and rename the names to abc... . In my opinion, jdgui is a decompiler, not a deobfuscator.(if you are finding a deobfuscator, you can search 'deobfuscator' in github.)

**Comment by emmanue1** [comment]
Thank you @Yun-Shan, nice demonstration.
@cyfex, could you download a sample for me to study the problem?

**Comment by cyfex** [comment]
Sorry, I think I was confused with multiple decompilers I used in testing. This problem is actually well-solved in jd-gui. Sorry about the mis-posting
